repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.12.0
  hooks:
    - id: nbqa-black
      args: ["--nbqa-mutate"]
    - id: nbqa-pyupgrade
      args: ["--nbqa-mutate"]
    - id: nbqa-isort
      args: ["--nbqa-mutate"]
- repo: https://github.com/timothycrosley/isort
  rev: 5.8.0
  hooks:
    - id: isort
      args: ["--profile", "black"]
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.902
  hooks:
    - id: mypy
      args: [--ignore-missing-imports, --pretty, --show-error-codes]
- repo: https://gitlab.com/pycqa/flake8
  rev:  3.9.2
  hooks:
    - id: flake8
      args: ["--ignore=E501,W503,E203,E231"]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.4
  hooks:
  -   id: pyupgrade
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-docstring-first
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-yaml
      args: [--unsafe, --allow-multiple-documents]
    - id: check-json
    - id: no-commit-to-branch
